name: project1_test
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.0 # (เวอร์ชันล่าสุด ณ ตอนนี้, เช็ค pub.dev เผื่อมีอัปเดต)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/pasta/
    - assets/rice/
    - assets/burger/
    - assets/images/testfood.jpg
    - assets/chicken/
    - assets/popu_menu/
    - assets/noodle/
    - assets/burger/b2/
    - assets/burger/b1/
    - assets/burger/b3/
    - assets/rice/shop/r1/
    - assets/rice/shop/r2/
    - assets/rice/shop/r3/
    - assets/pasta/shop/p1/
    - assets/pasta/shop/p2/
    - assets/pasta/shop/p3/
    - assets/noodle/shop/n1/
    - assets/noodle/shop/n2/
    - assets/noodle/shop/n3/
    - assets/baegu/
    - assets/gati/
    - assets/mayong/
    - assets/pakgad/
    - assets/phoenix/
    - assets/shrimp/
    - assets/tomato/
    - assets/profile_pic/
